apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-b
  labels: 
    app: day11-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: day11-backend
  template:
    metadata:
      labels:
        app: day11-backend
    spec:
      containers:
        - name: containers-b
          image: maulik010101/day11-backend:latest
          ports:
            - containerPort: 3000
          env:
            - name: MONGO_URL
              value: "$secrets.MONGO_URL"
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10