apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-f
spec:
  replicas: 2
  selector:
    matchLabels:
      app: day11-frontend
  template:
    metadata:
      labels:
        app: day11-frontend
    spec:
      containers:
        - name: containers-f
          image: maulik010101/day11-frontend:latest
          ports:
            - containerPort: 80
          env:
            - name: VITE_BACKEND_URL
              value: "http://backend:3000"
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10